volumes:
  database-data:
  pgadmin-data:
  redis-data:
  backend-data:
  static-volume:
  media-volume:

services:
  db:
    container_name: postgres_container
    image: postgres:16
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB}
    restart: always
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - "${PG_EXTERNAL_PORT}:${PG_PORT}"

  articler:
    container_name: articler_django_container
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${EXTERNAL_PORT}:${PORT}"
    command: >
      sh -c "
        python manage.py collectstatic --noinput &&
        python manage.py migrate &&
        python server.py"
    volumes:
      - static-volume:/backend/static
      - media-volume:/backend/media
      - backend-data:/backend
    depends_on:
      - db

  celery:
    container_name: celery
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A config worker -l INFO
    volumes:
      - backend-data:/backend
    depends_on:
      - articler

  nginx:
    container_name: nginx_container
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - "${NGINX_EXTERNAL_PORT}:${NGINX_PORT}"
    volumes:
      - static-volume:/backend/static
      - media-volume:/backend/media
    depends_on:
      - articler

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:7
    env_file:
      - .env
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
    ports:
      - "${PGADMIN_EXTERNAL_PORT}:${PGADMIN_PORT}"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  redis:
    container_name: redis_container
    image: redis:7.2.4-alpine
    restart: always
    ports:
      - "${REDIS_EXTERNAL_PORT}:${REDIS_PORT}"
    volumes:
      - redis-data:/data
    depends_on:
      - articler